### ISSUE TITLE
ResetPassword fails

### ISSUE THREAD

**Issue by ILABUTK** [francescomalatesta/laravel-api-boilerplate-jwt#78] opened 2019-01-31 17:11 UTC
Inside the ResetPasswordController.php:

1. resetPassword fails. It always throws 500 error. I traced to the $response which gives "password.token".

2. In the reset function: should it be: 
$user->password = bcrypt($password);

**Comment by francescomalatesta** [comment] 2019-04-18 21:46
Hey there! I don't think I understood well the problem. However, I just added continuous integration with Travis CI for tests with the last update. If the problem is still here I should see some failing tests. Closing it for the moment.

**Closed as completed by francescomalatesta** 2019-04-18 21:46 UTC

**Comment by aidataguy** [comment] 2019-07-10 09:32
Hey Frances, 

I am facing the same issue when I am trying to do a password reset. It keeps throwing error 500.. I am passing the required parameters in postman body. Upon tracing, I have found that when API is called, it skips checking the password it gets password.passwords instead of getting password.reset. and at the end hits **throw new HttpException(500);** . I am following all the steps but it seems that something is missing would really appreciate any help on this one.. .
